### PR TITLE
Fix: Allow Most chars for variable Values

### LINKED ISSUE #25: Allow any String as Variable Value, not just identifiers
Currently Tcases only allows variable values that are valid identifiers according to DefUtils.isIdentifier, meaning matching the regex ```"[\\w\\-]+"``` (alphabetic letters, numbers, underscores, hyphens).

However, for unit testing, special symbols are frequently part of the input to test. The Tcases restriction forces test designers to always map from abstract identifiers of values to actual values.

A PR shows one way to achieve this #27

For escaping/unescaping, commons-lang3 has StringEscapeUtils.

EDIT: complely rewrote the bug description.

### PR DESCRIPTION
**Pull request by tkruse**
Fix #25: allow any string except null as var value. XML-Unescaping is already done by the SAXParser, no code change needed. But allowing blanks for values required relaxing SystemTestDocReader. Identifiers could also be relaxed in the future that way (I see no reason beyond western-thinking esthetics to restrict to ascii Java word chars), but that is not so urgent for me, programmers should use ASCII for actual identifiers.

* [ ] TODO Fix failing tests, add tests for newly valid non-word characters (blank, japanese, special)

### CODE REVIEW

File: tcases-lib/src/main/java/org/cornutum/tcases/DefUtils.java [hunk 1]
```diff
@@ -77,5 +100,6 @@ public static void assertPropertyIdentifiers( Collection<String> properties) thr
     }
 
   private static final Pattern identifierRegex_ = Pattern.compile( "[\\w\\-]+");
+  private static final Pattern varValueRegex_ = Pattern.compile( "[^\\p{Cntrl}]*");
```
Comment (tkruse) [inline tcases-lib/src/main/java/org/cornutum/tcases/DefUtils.java]: avoiding chars like newline, escape, bell. Those could be encoded in XML1.1, but the SAX parser fails to recognize them.

File: tcases-lib/src/main/java/org/cornutum/tcases/io/SystemTestDocReader.java [hunk 2]
```diff
@@ -194,8 +202,7 @@ public String toIdPath( String attributeName, String attributeValue) throws SAXE
      */
     public String getAttribute( Attributes attributes, String attributeName)
       {
-      String value = attributes.getValue( attributeName);
-      return StringUtils.isBlank( value)? null : value;
```
Comment (tkruse) [inline tcases-lib/src/main/java/org/cornutum/tcases/io/SystemTestDocReader.java]: a single whitespace seems like an important boundary test case value to me, for testing various functions.

File: tcases-lib/src/main/java/org/cornutum/tcases/util/XmlWriter.java [hunk 3]
```diff
@@ -125,7 +128,7 @@ public void writeAttribute( String name, String value)
     print( " ");
     print( name);
     print( "=\"");
-    print( value);
+    print( StringEscapeUtils.escapeXml10(value));
```
Comment (tkruse) [inline tcases-lib/src/main/java/org/cornutum/tcases/util/XmlWriter.java]: not sure about all the differences between XML 1.0 and 1.1. This one suggests to go with 1.0 when in doubt: https://stackoverflow.com/questions/6260975/should-i-learn-xml-1-0-or-xml-1-1

**Comment by kerrykimbrough** [comment]
These changes seem basically OK. But I don't see any new unit tests to verify them.

**Comment by tkruse** [comment]
Yes, new tests need to be added, my free time is almost over, but I can work on adding tests next week.

**Comment by tkruse** [comment]
I have added more tests, and an equivalent change to SystemInputDefReader. Also I allowed whitespace and some control characters additionally, as they can be represented in XML1.1.

Some control characters cannot be parsed with the JDK parser however, so users would need to add a more XML1.1 compliant parser on the classpath, such as in maven adding simply:

    <dependency>
      <groupId>xerces</groupId>
      <artifactId>xercesImpl</artifactId>
      <version>2.12.0</version>
      <scope>runtime</scope>
    </dependency>

This replaces the SAXParser implementation automatically. I manually added to tests and saw that additional control character sequences can be parsed that way. But I did not add tests for that since tcases probably should not depend on xerces.

For other identifiers such as System and function name, I now think it would be preferable to allow international character sets, but that's more of a nuisance than a blocker, so up to you.

For properties I wish I could use some more characters like `{[]}=%#`, to auto-generate property names that do not clash with user-properties easily, and look decent. Not sure if you are willing to negotiate about that.

**Comment by kerrykimbrough** [comment]
> For other identifiers such as System and function name, I now think it would be preferable to allow international character sets

I agree -- see new issue #30. This has to be done carefully, but I will investigate soon.

**Comment by kerrykimbrough** [comment]
> For properties I wish I could use some more characters like {[]}=%#, to auto-generate property names 

For now, perhaps prefixing with something like `"__"` might be a reasonable convention.

File: tcases-lib/src/main/java/org/cornutum/tcases/util/XmlWriter.java [hunk 4]
```diff
@@ -125,7 +128,7 @@ public void writeAttribute( String name, String value)
     print( " ");
     print( name);
     print( "=\"");
-    print( value);
+    print( NumericEntityEscaper.below(0x20).translate(StringEscapeUtils.escapeXml11(value)));
```
Comment (kerrykimbrough) [inline tcases-lib/src/main/java/org/cornutum/tcases/util/XmlWriter.java]: Should add a comment to explain this translation. For example, why are both NumericEntityEscaper and StringEscapeUtils required?
